name: Extract Unique Countries from URL

on:
  workflow_dispatch:

jobs:
  extract-countries:
    runs-on: ubuntu-latest
    steps:
      - name: Download allproxy.txt
        run: |
          curl -o allproxy.txt https://raw.githubusercontent.com/stpdwrld/Stupid-Tunnel/refs/heads/main/allproxy.txt

      - name: Extract unique countries
        run: |
          cut -d',' -f3 allproxy.txt | sort | uniq > countries.txt

      - name: Show extracted countries
        run: cat countries.txt

      - name: Save to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull
          git add countries.txt
          git commit -m "Update countries list from allproxy.txt"
          git push
